development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: rs_hacks_development

test:
  adapter: postgresql
  encoding: unicode
  database: rs_hacks_test

production:
  adapter: postgresql
  encoding: unicode
  database: rs_hacks_production
