development:
  secret_key_base: an_insecure_secret_token_key_which_should_not_be_used_in_production

test:
  secret_key_base: an_insecure_secret_token_key_which_should_not_be_used_in_production

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
